### ISSUE TITLE
wrong title

### ISSUE THREAD

**Issue by napo** [DanielePassabi/DanielePassabi.github.io#1]
The title of the course is "Project of Geospatial Analysis and Representation for <del>Big</del> **_Data Science_"**

Line 188 in this code

https://github.com/DanielePassabi/DanielePassabi.github.io/blob/master/uni/geo/nb/3_Analysis_of_House_Sale_and_Rent_Cost_in_Province_of_Udine_R.html#L188

**Comment by DanielePassabi** [comment]
Apparently I keep thinking of the name of my Bachelor's degree... fixed!
